# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c06004829d33351375dec2016e8e3f08d911fb6b0c7934ef864256c97ba67849c2bb5b7c90874f76c0f735ae949525496dc8a099e55a189526903633b5e1214e

test:
  secret_key_base: c979d5393ffff2cd7a8657993b936f1407e1fb93df081ef48ab6998a0863bccaca3ae286928a2485da1f301ded7995a1df485b81e057652fe78838802c518127

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
